language: node_js
cache:
  directories:
    - ~/.npm

notifications:
  email: false

node_js:
  - '9'

jobs:
  include:
    - stage: test
      script: npm run ci
    - stage: publish
      if: branch = master
      script: echo 'Running semantic-release to determine release and publish...'
